/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkCreateCS {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CkCreateCS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CkCreateCS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkCreateCS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkCreateCS() {
    this(chilkatJNI.new_CkCreateCS(), true);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkCreateCS_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkCreateCS_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkCreateCS_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkCreateCS_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkCreateCS_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkCreateCS_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public void get_LastErrorHtml(CkString str) {
    chilkatJNI.CkCreateCS_get_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkCreateCS_lastErrorHtml(swigCPtr, this);
  }

  public void get_LastErrorText(CkString str) {
    chilkatJNI.CkCreateCS_get_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorText() {
    return chilkatJNI.CkCreateCS_lastErrorText(swigCPtr, this);
  }

  public void get_LastErrorXml(CkString str) {
    chilkatJNI.CkCreateCS_get_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkCreateCS_lastErrorXml(swigCPtr, this);
  }

  public boolean get_LastMethodSuccess() {
    return chilkatJNI.CkCreateCS_get_LastMethodSuccess(swigCPtr, this);
  }

  public void put_LastMethodSuccess(boolean newVal) {
    chilkatJNI.CkCreateCS_put_LastMethodSuccess(swigCPtr, this, newVal);
  }

  public boolean get_ReadOnly() {
    return chilkatJNI.CkCreateCS_get_ReadOnly(swigCPtr, this);
  }

  public void put_ReadOnly(boolean newVal) {
    chilkatJNI.CkCreateCS_put_ReadOnly(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkCreateCS_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkCreateCS_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public void get_Version(CkString str) {
    chilkatJNI.CkCreateCS_get_Version(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String version() {
    return chilkatJNI.CkCreateCS_version(swigCPtr, this);
  }

  public CkCertStore CreateFileStore(String path) {
    long cPtr = chilkatJNI.CkCreateCS_CreateFileStore(swigCPtr, this, path);
    return (cPtr == 0) ? null : new CkCertStore(cPtr, true);
  }

  public CkCertStore CreateMemoryStore() {
    long cPtr = chilkatJNI.CkCreateCS_CreateMemoryStore(swigCPtr, this);
    return (cPtr == 0) ? null : new CkCertStore(cPtr, true);
  }

  public CkCertStore CreateRegistryStore(String regRoot, String regPath) {
    long cPtr = chilkatJNI.CkCreateCS_CreateRegistryStore(swigCPtr, this, regRoot, regPath);
    return (cPtr == 0) ? null : new CkCertStore(cPtr, true);
  }

  public CkCertStore OpenChilkatStore() {
    long cPtr = chilkatJNI.CkCreateCS_OpenChilkatStore(swigCPtr, this);
    return (cPtr == 0) ? null : new CkCertStore(cPtr, true);
  }

  public CkCertStore OpenCurrentUserStore() {
    long cPtr = chilkatJNI.CkCreateCS_OpenCurrentUserStore(swigCPtr, this);
    return (cPtr == 0) ? null : new CkCertStore(cPtr, true);
  }

  public CkCertStore OpenFileStore(String path) {
    long cPtr = chilkatJNI.CkCreateCS_OpenFileStore(swigCPtr, this, path);
    return (cPtr == 0) ? null : new CkCertStore(cPtr, true);
  }

  public CkCertStore OpenLocalSystemStore() {
    long cPtr = chilkatJNI.CkCreateCS_OpenLocalSystemStore(swigCPtr, this);
    return (cPtr == 0) ? null : new CkCertStore(cPtr, true);
  }

  public CkCertStore OpenOutlookStore() {
    long cPtr = chilkatJNI.CkCreateCS_OpenOutlookStore(swigCPtr, this);
    return (cPtr == 0) ? null : new CkCertStore(cPtr, true);
  }

  public CkCertStore OpenRegistryStore(String regRoot, String regPath) {
    long cPtr = chilkatJNI.CkCreateCS_OpenRegistryStore(swigCPtr, this, regRoot, regPath);
    return (cPtr == 0) ? null : new CkCertStore(cPtr, true);
  }

  public boolean SaveLastError(String path) {
    return chilkatJNI.CkCreateCS_SaveLastError(swigCPtr, this, path);
  }

}
